---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-ebpf-profiler
  namespace: observability
  labels:
    app: opentelemetry-ebpf-profiler
spec:
  selector:
    matchLabels:
      app: opentelemetry-ebpf-profiler
  template:
    metadata:
      labels:
        app: opentelemetry-ebpf-profiler
    spec:
      containers:
        - name: opentelemetry-ebpf-profiler
          image: ctlptl-registry:5000/opentelemetry-ebpf-profiler:latest
          securityContext:
            privileged: true
          command: ["/opentelemetry-ebpf-profiler"]
          args:
            - "-collection-agent=otel-collector.observability.svc:4317"
            # - "-t=all"
            - "-disable-tls"
            - "-bpf-log-level=2"
            - "-probabilistic-threshold=50"
            - "-probabilistic-interval=2m30s"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
