---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
        - name: sample-node-app
          image: ctlptl-registry:5000/sample-node-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-node-app
  namespace: default
spec:
  selector:
    app: sample-node-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-node-app
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: sample-node-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-node-app
                port:
                  number: 8080
